# CodeRabbit Configuration
# This file configures CodeRabbit's code review behavior for your repository

# Custom instructions for CodeRabbit
# These instructions help CodeRabbit understand your codebase and review priorities
instructions: |
  This is a Learning Management System (LMS) built with:
  - Frontend: React 18, TypeScript, Vite, Tailwind CSS
  - Backend: Node.js, Express.js, MongoDB, Mongoose
  
  Please focus on:
  - Security best practices (especially for authentication and authorization)
  - Performance optimization
  - Code maintainability
  - TypeScript type safety
  - React best practices
  - Express.js best practices
  - MongoDB query optimization

# Paths to ignore during reviews
ignore:
  - "**/node_modules/**"
  - "**/dist/**"
  - "**/build/**"
  - "**/.git/**"
  - "**/coverage/**"
  - "**/*.min.js"
  - "**/*.min.css"
  - "**/package-lock.json"
  - "**/yarn.lock"
  - "**/.env*"
  - "**/uploads/**"
