// Types for consumers; implementation lives in shared/grading (ESM for Vite, CJS for Node).

export type {
  Assignment,
  Group,
  GroupWithGrades,
  GradingPolicyConfig,
  ResolvedGradingPolicy,
  Course,
  Grades,
  GradebookCellMarker,
  GradebookCellExport,
} from './gradeUtils.types';

export {
  calculateFinalGradeWithWeightedGroups,
  calculateCurrentGradeWithWeightedGroups,
  calculateProjectedFinalGradeWithWeightedGroups,
  computeGroupPointTotals,
  getWeightedGradeForStudent,
  getLetterGrade,
  createGroupTotals,
  isAssignmentGroupActive,
  assignmentContributesToGrade,
  applyAssignmentToGroupTotals,
  assignmentMaxPoints,
  isUnpublished,
  hasSubmissionForAssignment,
  EXCUSED_GRADE,
  isExcusedGrade,
  buildGradesMapForStudent,
  resolveAssignmentGrade,
  getGradebookCellForExport,
  DEFAULT_GRADING_POLICY,
  DEFAULT_GRADE_SCALE,
  resolveGradingPolicy,
  courseContextFromResolvedPolicy,
  enrichResolvedForAssignmentOrder,
  validateGradingPolicy,
  getGpaPoints,
  extractPolicyVersion,
  diffPolicies,
  summarizePolicyDiff,
  getGradingEngineVersion,
  GRADING_ENGINE_VERSION,
  GRADE_STATUS,
  GRADE_STATUS_LABELS,
  resolveSubmissionGradeStatus,
  gradebookCellFromStatus,
  hasSubmissionScore,
  isScoreReleased,
  releaseModeForAssignment,
  mapWorkflowStateToGradeStatus,
  mapGradeStatusToWorkflowState,
  getGradeStatusLabel,
  shouldShowStudentStatusBadge,
  isExtraCreditGroup,
  isExtraCreditAssignment,
  extraCreditEnabled,
  assignmentBonusPoints,
  applyExtraCreditToCourseTotal,
} from '@lms-shared/grading';
